# Generated by Django 4.2 on 2023-04-28 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("media_post", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="hashtag",
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
