# Generated by Django 4.2 on 2023-04-25 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userprofile",
            name="website",
            field=models.URLField(blank=True, default="URL not defined", null=True),
        ),
    ]
