# Generated by Django 4.2 on 2023-04-28 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0003_follow"),
    ]

    operations = [
        migrations.AlterField(
            model_name="follow",
            name="follower",
            field=models.ManyToManyField(
                blank=True, null=True, related_name="following", to="user.userprofile"
            ),
        ),
        migrations.AlterField(
            model_name="follow",
            name="following",
            field=models.ManyToManyField(
                blank=True, null=True, related_name="followers", to="user.userprofile"
            ),
        ),
    ]
